✨ Feat : 첫번째 로그인 여부 확인 로직 추가
BulletBoxProject/BE-project pull request #224
Opened 2023-02-01 19:31 UTC by Jaekyeong1

## PR 체크사항
PR이 다음 사항을 만족하는지 확인해주세요.

- [x] PR 제목 규칙
- [x] 커밋 메시지 작성 가이드라인
- [x] 라벨, 담당자, 리뷰어 지정

## PR 타입
어떤 유형의 PR인지 체크해주세요.

- [ ] Bugfix
- [x] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Documentation content changes
- [ ] Other... Please describe:

## PR 설명
첫번째 로그인 여부 확인 로직 추가

## 작업사항
- 첫번째 로그인 여부 확인 로직 추가

## 연결 이슈 close

close #223

2023-02-01 19:40 UTC, hangj97 reviewed
고생하셨습니다~~ 코멘트 확인 부탁드리겠습니다!

2023-02-01 19:40 UTC, hangj97 commented on src/main/java/com/hanghae/bulletbox/member/service/MemberService.java
> +    public ResponseFirstLoginDto login(MemberDto memberDto, HttpServletResponse response) {
P2; 해당 메서드는 로그인 API 입니다!
신규 회원을 판별하는 것은 해당 API 기능의 일부라고 생각합니다. 그래서 전체를 아우르는 이름으로 변경이 필요하다고 생각합니다.

ex) **ResponseLoginDto**

2023-02-02 01:31 UTC, minokim1080 requested changes
고생하셨습니다! 리뷰 한번 확인해주시면 감사하겠습니다 :)

2023-02-02 01:31 UTC, minokim1080 commented on src/main/java/com/hanghae/bulletbox/member/service/MemberService.java
> +        firstLogin = true;
p1) 현재 로직에서 if 문을 들어가든 안 들어가든 무조건 81번째 줄이 실행되게 됩니다!

2023-02-02 01:31 UTC, minokim1080 commented on src/main/java/com/hanghae/bulletbox/member/dto/MemberDto.java
> +    public static MemberDto toMemberDto(ResponseFirstLoginDto responseFirstLoginDto){
p2) 혹시 이 메소드는 어디서 사용될까요?? 응답 DTO가 다시 MemberDto로 변환될 일이 없어 보여서 여쭤봅니다..!

2023-02-02 05:27 UTC, Jaekyeong1 commented on src/main/java/com/hanghae/bulletbox/member/dto/MemberDto.java
> +    public static MemberDto toMemberDto(ResponseFirstLoginDto responseFirstLoginDto){
생각해보니 그렇군용 수정했습니다

2023-02-02 05:28 UTC, Jaekyeong1 commented on src/main/java/com/hanghae/bulletbox/member/service/MemberService.java
> +        firstLogin = true;
넵 감사합니다 ! 새벽에 비몽사몽하며 작성해서 맞는지도 확인 안하고 그냥 머지 해버렸던거같아요 ,,
수정했습니다

2023-02-02 05:28 UTC, Jaekyeong1 commented on src/main/java/com/hanghae/bulletbox/member/service/MemberService.java
> +    public ResponseFirstLoginDto login(MemberDto memberDto, HttpServletResponse response) {
굿입니다요 !

2023-02-02 05:31 UTC, minokim1080 approved these changes

2023-02-02 05:32 UTC, merged

2023-02-02 05:32 UTC, hangj97 approved these changes
고생하셨습니다!!